services:
  mysql:
    image: mysql:8.0
    container_name: quantitymeasurementdb_v2
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: quantity_db
      MYSQL_USER: quantity_user
      MYSQL_PASSWORD: quantity_pass

    ports:
      - "3307:3306"

    volumes:
      - quantitymeasurement-dbdata:/var/lib/mysql

    networks:
      - quantitymeasurement-net

  backend:
    image: 043784343117.dkr.ecr.us-east-2.amazonaws.com/quantitymeasurement-backend:v2
    container_name: qm-app-backend

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    networks:
      - quantitymeasurement-net

volumes:
  quantitymeasurement-dbdata:

networks:
  quantitymeasurement-net:
    driver: bridge
